version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: local-mongodb
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:27017"
    env_file: .env
    environment:
      # used by the official image to bootstrap admin user
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
      - ./infra/mongo/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://localhost:27017", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  # optional: web UI to inspect db (visit http://localhost:8081)
  mongo-express:
    image: mongo-express:1
    container_name: local-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data:
